In [1]:
import pandas as pd

pd.set_option("display.max_columns", None)
import warnings
warnings.filterwarnings('ignore')

In [2]:

disaster_declarations = pd.read_csv(r"../dataset/disaster_declarations.csv")
pub_ass_funding = pd.read_csv(r"../dataset/pa_funding_details.csv")

In [3]:
disaster_declarations

,disasterNumber,state,incidentType,declarationDate,incidentBeginDate,incidentEndDate,declarationType
0,5529,OR,Fire,2024-08-09T00:00:00.000Z,2024-08-08T00:00:00.000Z,NaN,FM
1,5528,OR,Fire,2024-08-06T00:00:00.000Z,2024-08-04T00:00:00.000Z,NaN,FM
2,5527,OR,Fire,2024-08-02T00:00:00.000Z,2024-08-02T00:00:00.000Z,NaN,FM
3,4312,CA,Severe Storm,2017-05-02T00:00:00.000Z,2017-02-08T00:00:00.000Z,2017-02-11T00:00:00.000Z,DR
4,4251,AL,Severe Storm,2016-01-21T00:00:00.000Z,2015-12-23T00:00:00.000Z,2015-12-31T00:00:00.000Z,DR
...,...,...,...,...,...,...,...
69761,9,TX,Flood,1953-06-19T00:00:00.000Z,1953-06-19T00:00:00.000Z,1953-06-19T00:00:00.000Z,DR
69762,8,IA,Flood,1953-06-11T00:00:00.000Z,1953-06-11T00:00:00.000Z,1953-06-11T00:00:00.000Z,DR
69763,7,MA,Tornado,1953-06-11T00:00:00.000Z,1953-06-11T00:00:00.000Z,1953-06-11T00:00:00.000Z,DR
69764,2,TX,Tornado,1953-05-15T00:00:00.000Z,1953-05-15T00:00:00.000Z,1953-05-15T00:00:00.000Z,DR
69765,1,GA,Tornado,1953-05-02T00:00:00.000Z,1953-05-02T00:00:00.000Z,1953-05-02T00:00:00.000Z,DR

In [4]:
disaster_declarations.nunique()

disasterNumber       5160
state                  59
incidentType           27
declarationDate      3583
incidentBeginDate    3288
incidentEndDate      3349
declarationType         3
dtype: int64

In [5]:
pub_ass_funding

,disasterNumber,incidentType,damageCategoryCode,stateNumberCode,gmProjectId,countyCode,projectAmount,federalShareObligated,totalObligated
0,1603,Hurricane,E,22,901765,75,18602329.78,18602329.78,18788818.15
1,1586,Severe Storm(s),G,4,899650,5,112090.72,84068.04,88196.37
2,1586,Severe Storm(s),G,4,899657,5,773645.98,580234.49,603034.89
3,3384,Hurricane,B,72,51291,3,59779.98,44834.99,44834.99
4,3384,Hurricane,B,72,55081,57,20333.13,15249.85,15249.85
...,...,...,...,...,...,...,...,...,...
784930,4834,Hurricane,Z,12,966806,115,2961.45,2961.45,2961.45
784931,4878,Severe Storm(s),C,47,961633,71,58239.38,43679.54,43679.54
784932,4879,Flood,F,48,961529,435,104057.32,78042.99,78042.99
784933,4881,Flood,B,41,966133,11,1093.20,819.91,819.91
784934,4889,Severe Storm(s),B,37,966460,145,48141.45,36106.09,36106.09

In [6]:
pub_ass_funding.nunique()

disasterNumber             1707
incidentType                 26
damageCategoryCode            9
stateNumberCode              57
gmProjectId              784935
countyCode                  325
projectAmount            642130
federalShareObligated    638146
totalObligated           667041
dtype: int64